<?php
		$catId =2;
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
		$currentStore = $storeManager->getStore();
		$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);           
		$subcats = $subcategory->getChildrenCategories();
        ?>

<div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-2 cat-list">
                    <h2 class="cat-title">DAMAS</h2>
					 <?php
            foreach ($subcats as $subcat) {
                if ($subcat->getIsActive()) {

                    $subcat_url = $subcat->getUrl();
                    echo $subcat_img = $subcategory->getImageUrl();
					echo $mediaUrl.$subcat_img;
                    $placeholder_img = "/media/placeholder.png";
					$subcatid=$subcat->getId();
                    ?>
				<div class="main-cat">
                       <a href="<?php echo $subcat_url; ?>">
                            <h2 class="main-cat-tilte"><?php echo $subcat->getName(); ?></h2>
                        </a>
						 <ul>
						<?php 
						$subcategorychild = $objectManager->create('Magento\Catalog\Model\Category')->load($subcatid);           
						$subcatchilds = $subcategorychild->getChildrenCategories();
						     foreach ($subcatchilds as $subcatchild) {
							if ($subcatchild->getIsActive()) {

								$subcatchild_url = $subcatchild->getUrl();
								$subcatchild_img = "";
								$placeholder_img = "/media/placeholder.png";
								$subcatchildid=$subcatchild->getId();
						?>
                       
                            <li><a href="<?php echo $subcatchild_url; ?>"><?php echo $subcatchild->getName(); ?></a></li>
                       
							<?php }
							}?>
						 </ul>
                    </div>
                    <?php
                }
            }
            ?>
                </div>
                <div class="col-md-10 col-sm-10 col-xs-12">
                    <!-- Banner -->
                    <div class="swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kit2pares_1.jpg'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kit2pares_1.jpg'); ?>"></div>
                        </div>
                        <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->
                        
                        <!-- Add Arrows -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                    <div class="clearfix"></div>
                    <!-- Brand Show -->
                    <div class="swiper-container-brand bottom-margin top-margin margin-15">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/adidas.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/dc.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/flexi.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kswiss.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/levis.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/newbalance.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/nike.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/vans.gif'); ?>"></div>
                        </div>
                        <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->
                        
                        <!-- Add Arrows 
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>-->
                    </div>
                    <div class="clearfix"></div>
                    <div class="cat-container margin-15">
                        <h2 class="cat-individual-title"><span>-</span>Zapatos<span>-</span></h2>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/zapatillas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <div class="clearfix"></div>
                            <p class="sub-title">Zapalillas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6 ">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/flats.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div>
                            <div class="clearfix"></div> 
                            <p class="sub-title">Flats</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/botas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Botas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/sandalias.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Sandalias</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/pantuflas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Pantuflas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/tenis.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Tenis</p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                     <div class="cat-container margin-15">
                        <h2 class="cat-individual-title"><span>-</span>ROPA<span>-</span></h2>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/faldas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Faldas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/vestidos.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Vestidos</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/pantalones.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Pantalones</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/shorts.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Shorts</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/blusas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Blusas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/playeras.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Playeras</p>
                        </div>
                    </div>
                    <div class="clearfix"></div> 
                    <div class="cat-container margin-15">
                        <h2 class="cat-individual-title"><span>-</span>Maquillaje<span>-</span></h2>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/rostro.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Rostro</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/ojos.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Ojos</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/labios.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Labios</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/unas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <div class="clearfix"></div>
                            <p class="sub-title">Unas</p>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>