<div class="container-fluid no-padding">
    
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 no-padding">
            <!-- Banner -->
            <div class="banner swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/home.png'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kit2pares_1.jpg'); ?>"></div>
                </div>
                <!-- Add Pagination -->
                <div class="swiper-pagination"></div>

                <!-- Add Arrows -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
            <div class="clearfix"></div>
            <!-- Brand Show -->
            <div class="brand swiper-container">
                <h2 class="cat-individual-title">Marcas Destacadas</h2>
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/adidas.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/dc.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/flexi.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kswiss.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/levis.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/newbalance.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/nike.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/vans.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/adidas.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/dc.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/flexi.gif'); ?>"></div>
                    <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kswiss.gif'); ?>"></div>
                </div>
                <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->

                <!-- Add Arrows -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
            <div class="clearfix"></div>
            <div class="tendencias">
                <h2 class="cat-individual-title">Tendencias</h2>
                <div class="tendencias-container">
                    <div class="col-md-4 col-sm-4 col-xs-4 h-600">
                        <img class="h-600 no-padding" src="<?php echo $this->getViewFileUrl('images/s1.png'); ?>">
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4 h-300">
                        <img class="h-300" src="<?php echo $this->getViewFileUrl('images/s6.png'); ?>">
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4 h-300">
                        <img class="h-300" src="<?php echo $this->getViewFileUrl('images/s7.png'); ?>">
                    </div>
                    <div class="col-md-8 col-sm-8 col-xs-8 h-300">
                        <img class="h-300" src="<?php echo $this->getViewFileUrl('images/s5.png'); ?>">
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4 h-300">
                        <img class="h-300 no-padding" src="<?php echo $this->getViewFileUrl('images/s2.png'); ?>">
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4 h-300">
                        <img class="h-300" src="<?php echo $this->getViewFileUrl('images/s3.png'); ?>">
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4 h-300">
                        <img class="h-300" src="<?php echo $this->getViewFileUrl('images/s4.png'); ?>">
                    </div>
                </div>

            </div>

            <!-- Catalog -->
            <div class="clearfix"></div>
            <div class="catlog swiper-container margin-15">

                <h2 class="cat-individual-title">Catalogos</h2>
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/zapatillas.png'); ?>"><p class="slider-title">Botas</p>
                    <p class="slider-price">2016-2017</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/flats.png'); ?>"><p class="slider-title">escolar
</p>
                    <p class="slider-price">2016</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/botas.png'); ?>"><p class="slider-title">caballeros</p>
                    <p class="slider-price">2016-2017</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/sandalias.png'); ?>"><p class="slider-title">mochilas</p>
                    <p class="slider-price">2016</p>
                        </div></div>
                     <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/zapatillas.png'); ?>"><p class="slider-title">Botas</p>
                    <p class="slider-price">2016-2017</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/flats.png'); ?>"><p class="slider-title">escolar
</p>
                    <p class="slider-price">2016</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/botas.png'); ?>"><p class="slider-title">caballeros</p>
                    <p class="slider-price">2016-2017</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/sandalias.png'); ?>"><p class="slider-title">mochilas</p>
                    <p class="slider-price">2016</p>
                        </div></div>
                </div>
                <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->

                <!-- Add Arrows -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
            <div class="clearfix"></div>
            <!-- Catalog -->
            <div class="zapatos swiper-container margin-15">
                <h2 class="cat-individual-title">Zapatos</h2>
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/c1.png'); ?>"><p class="slider-title">BOHO CHIC</p>
                    <p class="slider-price">$112</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/c2.png'); ?>"><p class="slider-title">BOHO CHIC</p>
                    <p class="slider-price">$112</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/c3.png'); ?>"><p class="slider-title">BOHO CHIC</p>
                    <p class="slider-price">$112</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/c4.png'); ?>"><p class="slider-title">BOHO CHIC</p>
                    <p class="slider-price">$112</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/c5.png'); ?>"><p class="slider-title">BOHO CHIC</p>
                    <p class="slider-price">$112</p>
                        </div></div>
                    <div class="swiper-slide"><div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/c6.png'); ?>"><p class="slider-title">BOHO CHIC</p>
                    <p class="slider-price">$112</p>
                        </div></div>
                </div>
                <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->

                <!-- Add Arrows -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
            <div class="clearfix"></div>
            <!-- Catalog -->
            <div class="estilos swiper-container margin-15">

                <h2 class="cat-individual-title">Estilos</h2>
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-1.png'); ?>">
                            <p class="slider-title">BOHO CHIC</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-2.png'); ?>">
                            <p class="slider-title">PLAYERO</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-3.png'); ?>">
                            <p class="slider-title">FORMAL</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-4.png'); ?>">
                            <p class="slider-title">CASUAL</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-1.png'); ?>">
                            <p class="slider-title">BOHO CHIC</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-2.png'); ?>">
                            <p class="slider-title">PLAYERO</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-3.png'); ?>">
                            <p class="slider-title">FORMAL</p>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="col-12"><img src="<?php echo $this->getViewFileUrl('images/products/e-4.png'); ?>">
                            <p class="slider-title">CASUAL</p>
                        </div>
                    </div>
                </div>
                <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->

                <!-- Add Arrows -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>