<div class="container no-padding">
            <div class="row">
                <div class="col-md-2 col-sm-2 cat-list">
                    <h2 class="cat-title">DAMAS</h2>
                    <div class="main-cat">
                        <h2 class="main-cat-tilte">Zapatos</h2>
                        <ul>
                            <li>Zapalillas</li>
                            <li>Flats</li>
                            <li>Botas</li>
                            <li>Sandalias</li>
                            <li>Pantuflas</li>
                            <li>Tenis</li>
                        </ul>
                    </div>
                    <div class="main-cat">
                        <h2 class="main-cat-tilte">Ropa</h2>
                        <ul>
                            <li>Faldas</li>
                            <li>Vestidos</li>
                            <li>Pantalones</li>
                            <li>Shorts</li>
                            <li>Blusas</li>
                            <li>Playeras</li>
                        </ul>
                    </div>
                    <div class="main-cat">
                        <h2 class="main-cat-tilte">Maquillaje</h2>
                        <ul>
                            <li>Rostro</li>
                            <li>Ojos</li>
                            <li>Labios</li>
                            <li>Unas</li>
                        </ul>
                    </div>
                    
                </div>
                <div class="col-md-10 col-sm-10 col-xs-12 no-padding">
                    <!-- Banner -->
                    <div class="banner swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kit2pares_1.jpg'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/tacones_1.jpg'); ?>"></div>
                        </div>
                        <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->
                        
                        <!-- Add Arrows -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                    <div class="clearfix"></div>
                    <!-- Brand Show -->
                    <div class="swiper-container swiper-container-brand bottom-margin top-margin margin-15">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/adidas.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/dc.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/flexi.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/kswiss.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/levis.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/newbalance.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/nike.gif'); ?>"></div>
                            <div class="swiper-slide"><img src="<?php echo $this->getViewFileUrl('images/vans.gif'); ?>"></div>
                        </div>
                        <!-- Add Pagination 
                        <div class="swiper-pagination"></div>-->
                        
                        <!-- Add Arrows 
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>-->
                    </div>
                    <div class="clearfix"></div>

                  
                    <div class="cat-container margin-15">
                        <h2 class="cat-individual-title"><span>-</span>Zapatos<span>-</span></h2>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/zapatillas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <div class="clearfix"></div>
                            <p class="sub-title">Zapalillas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6 ">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/flats.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div>
                            <div class="clearfix"></div> 
                            <p class="sub-title">Flats</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/botas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Botas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/sandalias.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Sandalias</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/pantuflas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Pantuflas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/tenis.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Tenis</p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                     <div class="cat-container margin-15">
                        <h2 class="cat-individual-title"><span>-</span>ROPA<span>-</span></h2>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/faldas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Faldas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/vestidos.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Vestidos</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/pantalones.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Pantalones</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/shorts.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Shorts</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/blusas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Blusas</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/playeras.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Playeras</p>
                        </div>
                    </div>
                    <div class="clearfix"></div> 
                    <div class="cat-container margin-15">
                        <h2 class="cat-individual-title"><span>-</span>Maquillaje<span>-</span></h2>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/rostro.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Rostro</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/ojos.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Ojos</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/labios.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <p class="sub-title">Labios</p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                             
                            <div class="clearfix"></div>
                            <div class="sub-cat-image-container">
                                <img src="<?php echo $this->getViewFileUrl('images/products/unas.png'); ?>">
                                <div class="overlay">
                                    <div class="text"><img src="<?php echo $this->getViewFileUrl('images/link-interface-symbol.png'); ?>"></div>
                                </div>
                            </div> 
                            <div class="clearfix"></div>
                            <p class="sub-title">Unas</p>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>